### PR TITLE
New role - postgresql-props

### PR DESCRIPTION
**Pull request by mrsrvman**
Consolidation of roles (postgresql-databases,postgresql-users,postgresql-schemas) into one.

Ability to configure user rights and connection limits

### CODE REVIEW

**Comment by vitabaks** [comment]
@mrsrvman Hi! Thank you for your contribution to the development.

Please, return the roles to their original state (without consolidation), since these are different tasks. 

Next, you can add the necessary functionality to these roles.

**Comment by mrsrvman** [comment]
Without such consolidation, full user customization may not be possible, which may require the presence of a created base.
It is because of this that you have to create a user, create databases, configure the user (user privileges).

**Comment by vitabaks** [comment]
> Without such consolidation, full user customization may not be possible, which may require the presence of a created base.

there should be no problems if the necessary variables are specified in vars/main.yml

**Comment by mrsrvman** [comment]
Multiple roles do not give the correct execution order.
Merging roles gives you such control.
Variables in the request are unaffected and backwards compatible.

**Comment by vitabaks** [comment]
maybe we need a role "postgresql-privs"

https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_privs_module.html#ansible-collections-community-postgresql-postgresql-privs-module

**Comment by mrsrvman** [comment]
Such a role or task in the role is needed.
There is already a warning when using ansible.postgresql_user.priv.

You may also need to refactor the variables that describe the user and the relationship with the databases.

Now two dictionaries are used - user and bases.
Maybe it makes sense to make one - the user, his bases and possible privileges.

**Comment by vitabaks** [comment]
I think separate variables are needed for privileges

**Pull request closed without merging**
