### PR TITLE
Check cluster already installed

### PR DESCRIPTION
**Pull request by chlordk**
Make deployment stop if the cluster is already installed.

### CODE REVIEW

**Comment by vitabaks** [comment]
@chlordk 

We already have a similar check that does not allow deleting data for an already existing PostgreSQL instance

`check that data directory "{{ postgresql_data_dir }}" is not initialized`

https://github.com/vitabaks/postgresql_cluster/blob/master/roles/patroni/tasks/main.yml#L380

**Comment by vitabaks** [comment]
I understand you just want to perform this check at an earlier stage

**Comment by vitabaks** [comment]
I prefer not to add these tasks to the "Gathering facts from all servers" block \
for pre-checks there are pre_tasks for hosts: postgres_cluster

You can add "Update apt cache" before the task

**Comment by chlordk** [comment]
> We already have a similar check

Sorry. I must have missed it.

Just reject this PR.

**Pull request closed without merging**
