### PR TITLE
Fix yaml[octal-values] from skip_list

### PR DESCRIPTION
**Pull request by ThomasSanson**

### CODE REVIEW

**Comment by ThomasSanson** [comment]
Hello @vitabaks,

Could you please restart the GitHub Docker action ?

**Comment by vitabaks** [comment]
Ок

**Comment by ThomasSanson** [comment]
Great, it's done! Sometimes the issue comes from the timeout or the network during the Docker build, hence issue #374. 

This pull request is ready.

**Comment by vitabaks** [comment]
Thank you for your contribution! 

This work is very important for the further development of the project.

**Pull request merged**
