### PR TITLE
Revise ansible-lint to incorporate incremental changes for future adaptability

### PR DESCRIPTION
**Pull request by ThomasSanson**
The goal of this refactoring process would be to improve the maintainability and scalability of ansible-lint, making it easier to adapt and expand in the future.

### CODE REVIEW

**Comment by vitabaks** [comment]
@ThomasSanson Thank you for your contribution! 

Processing `skip_list` is something that has been demanding attention for a long time.

Please note that some PR is still open (under development). This means that the merging of this PR is possible only after the completion of the code change in other PRs.

**Comment by ThomasSanson** [comment]
@vitabaks 

I completely understand your perspective, and I want to shed some light on the changes I made. The main focus of my modifications was to refactor the skip_list, aiming at better anticipating and facilitating future work on the project.

Although my changes may seem minor, they are essential to streamline and prepare the codebase for further improvements and modifications. However, I understand if you have concerns regarding the potential impact of these changes on other aspects of the project.

If you wish, I can quickly carry out tests to assess the impacts of my modifications on other pull requests. My intention is to contribute positively to the project, ensuring my changes align well with existing and forthcoming work.

**Comment by vitabaks** [comment]
I understood you. Let me know if I need to merge into the master branch.

**Comment by ThomasSanson** [comment]
@vitabaks 

✔️ The merge between this branch and the pg_upgrade branch is ok (testing)

this pull request is ready for me

**Pull request merged**
