### PR TITLE
Scram passwords

### PR DESCRIPTION
**Pull request by sjstoelting**
I've added the variable password_encryption in vars/main.yml to have a single point for the encryption method.
The variable is used in PostgreSQL options, role examples, and PgBouncer options.

### CODE REVIEW

**Comment by vitabaks** [comment]
Thanks @sjstoelting  it looks great!

Do you have tried using the `postgresql_parameters.password_encryption` variable for `pgbouncer_auth_type` instead of defining a new variable?

**Comment by vitabaks** [comment]
> Do you have tried using the postgresql_parameters.password_encryption variable for pgbouncer_auth_type (and etc..) instead of defining a new variable?

We can leave it like this for now, and then I'll think about how to improve it

**Comment by sjstoelting** [comment]
No, I haven't considered  postgresql_parameters.password_encryption, let me give it a try.

**Comment by sjstoelting** [comment]
I've tried it with postgresql_parameters.password_encryption, that did not work.
Though, it could stay as is, or roles/pgbouncer/templates/pgbouncer.ini.j2 could use the variable  `password_encryption`.

**Comment by vitabaks** [comment]
> I've tried it with postgresql_parameters.password_encryption, that did not work.
Though, it could stay as is, or roles/pgbouncer/templates/pgbouncer.ini.j2 could use the variable password_encryption.

Well, thank you for taking the time to do this.

I modify this variables later.

**Pull request merged**
