### PR TITLE
Add firewalld/ufw support

### PR DESCRIPTION
**Pull request by redy01**

### CODE REVIEW

**Comment by vitabaks** [comment]
Hi @redy01 

Thank you for your contribution!

I see that the tests are failing with an error:` 'firewall_type' is undefined. 'firewall_type' is undefined`

**Comment by redy01** [comment]
Wired, because firewall_type is defined in vars/system.yml loaded in "pretasks" section

**Comment by SDV109** [comment]
@redy01, Hi, please rename your branch, I can't make a git clone for a branch named #501

**Comment by redy01** [comment]
Hi,
renamed to "add-firewalld_ufw"

________________________________

**Pull request closed without merging**
