### PR TITLE
requirements.dev: Update docker-py to version 6.1.0

### PR DESCRIPTION
**Pull request by vitabaks**
urllib3 v2 incompatibility: https://github.com/docker/docker-py/issues/3113

Release notes: https://github.com/docker/docker-py/releases/tag/6.1.0

### CODE REVIEW

**Comment by vitabaks** [comment]
However, it didn't work for me

```
 failed: [localhost] (item=10.172.0.20) => {"ansible_job_id": "j85150351689.2206", "ansible_loop_var": "item", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "j85150351689.2206", "ansible_loop_var": "item", "changed": true, "failed": 0, "finished": 0, "item": {"cgroupns_mode": "host", "command": "", "exposed_ports": ["2379/tcp", "2380/tcp", "8300/tcp", "8301/tcp", "8302/tcp", "8500/tcp", "8600/tcp", "8008/tcp", "5432/tcp", "6432/tcp"], "groups": ["etcd_cluster", "consul_instances", "master", "postgres_cluster", "balancers"], "hostname": "pgnode01", "image": "geerlingguy/docker-debian11-ansible:latest", "name": "10.172.0.20", "networks": [{"ipv4_address": "10.172.0.20", "name": "test_docker_network"}], "pre_build_image": true, "privileged": true, "volumes": ["/sys/fs/cgroup:/sys/fs/cgroup:rw"]}, "results_file": "/home/runner/.ansible_async/j85150351689.2206", "started": 1}, "msg": "Error connecting: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'", "results_file": "/home/runner/.ansible_async/j85150351689.2206", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```
https://github.com/vitabaks/postgresql_cluster/actions/runs/4897644464/jobs/8745917444

and I have [pinned](https://github.com/vitabaks/postgresql_cluster/pull/320/commits/5ee7dba243efe21114cb199fea561b74cfb57cf5) urllib3==1.26.15 so far.

**Comment by vitabaks** [comment]
FYI @ThomasSanson

**Comment by vitabaks** [comment]
the attempt to [update](https://github.com/vitabaks/postgresql_cluster/pull/320/commits/927ad27df5edece1eae621be0b6e73efd638c388) all packages is [unsuccessful](https://github.com/vitabaks/postgresql_cluster/actions/runs/4897776906/jobs/8746206133) so I'm [revert](https://github.com/vitabaks/postgresql_cluster/pull/320/commits/c498804270ec839bac54514ab3e3e67a2dc5af69) this commit.

**Comment by ThomasSanson** [comment]
Hello,

I will wait for this pull request to be merged and then I will address this issue: #311

**Pull request merged**
