### PR TITLE
Use makefile for molecule tests in CI/CD

### PR DESCRIPTION
**Pull request by vitabaks**
Ensure consistency between the development environment and CI/CD tests.

Related PR: https://github.com/vitabaks/postgresql_cluster/pull/305

### CODE REVIEW

**Comment by vitabaks** [comment]
```
AttributeError: 'Runtime' object has no attribute 'exec'
make: *** [.config/make/molecule.mak:4: molecule-test] Error 1
Error: Process completed with exit code 2.
```

@ThomasSanson do you have any idea why it doesn't work?

**Comment by ThomasSanson** [comment]
@vitabaks 
Unfortunately, I don't have any idea why you are getting this error. However, I will investigate the issue to help you resolve it.

I will increased the verbosity to obtain more information.

**Comment by ThomasSanson** [comment]
@vitabaks

Warning: There is an improperly handled breaking change in ansible-compat, which causes a malfunction in molecule. As a result, you should enforce the usage of ansible-compat==3.0.1 instead of version 4.0.1 (at least until the necessary fix is provided in molecule https://github.com/ansible-community/molecule/pull/3904 ).

To apply this version fix, add the following line to the requirements.dev.txt files :
`ansible-compat==3.0.1`

Additionally, this issue serves as another reason why I advocate for freezing the versions of dependencies – all versions, in fact.

**Comment by vitabaks** [comment]
@ThomasSanson Thank you so much for your help!

**Pull request merged**
