### PR TITLE
Changed PostgreSQL password encryption from md5 to scram-sha-256.

### PR DESCRIPTION
**Pull request by sjstoelting**
I switched password encryption away from insecure md5 to scram-sha-256, which is default in PostgreSQL 14.

### CODE REVIEW

**Comment by vitabaks** [comment]
Note that older clients might lack support for the SCRAM authentication mechanism, and hence not work with passwords encrypted with SCRAM-SHA-256.

I think it's worth adding a comment:

"`  # or ''md5" if your clients do not work with passwords encrypted with SCRAM-SHA-256`"

**Comment by sjstoelting** [comment]
It might also be necessary, to add a hint, that the PgBouncer configuration has to be changed, too.
Otherwise the login through PgBouncer will fail.

" # or ''md5" if your clients do not work with passwords encrypted with SCRAM-SHA-256, you have to change the PgBouncer configration in /roles/pgbouncer/templates/pgbouncer.ini.j2, too"

**Comment by vitabaks** [comment]
>  you have to change the PgBouncer configuration in /roles/pgbouncer/templates/pgbouncer.ini.j2, too

I think it's better to add the `pgbouncer_auth_type` variable to vars/main

**Comment by sjstoelting** [comment]
I'll create a new pull request, where I changed the authentication method handled by a variable.

**Pull request closed without merging**
