### PR TITLE
Set vm.nr_hugepages playbook 

### PR DESCRIPTION
**Pull request by chlordk**

### CODE REVIEW

**Comment by chlordk** [comment]
I'm not sure why this came with the PR???
> Merge branch 'vitabaks:master' into master

It was not supposed to be there.
Should I close this and make a new PR?

**Comment by chlordk** [comment]
@vitabaks Do you want a description of how to calculate `huge_pages` in README.md?
It will based on this description:
[Why Linux HugePages are Super Important for Database Servers: A Case with PostgreSQL](https://www.percona.com/blog/why-linux-hugepages-are-super-important-for-database-servers-a-case-with-postgresql/)

**Comment by vitabaks** [comment]
Thanks @chlordk 

I think it should be a role and not a poeybook.

**Comment by chlordk** [comment]
> I think it should be a role and not a plaeybook.

Oh, I just see that it is already there. I Just specified `vm.nr_hugepages` in `vars/system.yml` and it works fine.

So please reject this PR.

**Pull request closed without merging**
