### PR TITLE
Support Ubuntu 24.04; Install Patroni via deb/rpm package

### PR DESCRIPTION
**Pull request by vitabaks**
Add support for Ubuntu 24.04

UPD:

To ensure compatibility with Ubuntu 22.04 (and Python 3.12), the Patroni package will be installed from the deb/rpm package by default. The latest available version of the package will be installed from the Postgres repository.

You also have the option to choose the installation method using the pip package (variable `patroni_installation_method`) if you prefer this installation method or, for example, want to have better control over the version of the Patroni package that you install on the cluster.

Note: Consul package for OracleLinux missing in HashiCorp repository. Only the installation of a binary file is supported (consul_install_from_repo: false, patroni_installation_method: "pip")

### CODE REVIEW

**Comment by vitabaks** [comment]
The pysyncobj-0.3.12 package is not compatible with python3.12

```
root@pgnode01:/# pip3 install -r /tmp/requirements.txt 
Requirement already satisfied: urllib3>=1.25.9 in /usr/local/lib/python3.12/dist-packages (from -r /tmp/requirements.txt (line 1)) (2.2.1)
Collecting boto3 (from -r /tmp/requirements.txt (line 2))
  Using cached boto3-1.34.92-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 3)) (6.0.1)
Collecting requests>=2.25.1 (from -r /tmp/requirements.txt (line 4))
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: six>=1.7 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 5)) (1.16.0)
Requirement already satisfied: python-etcd<0.5,>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from -r /tmp/requirements.txt (line 6)) (0.4.5)
Collecting python-consul>=0.7.1 (from -r /tmp/requirements.txt (line 7))
  Using cached python_consul-1.1.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting click>=4.1 (from -r /tmp/requirements.txt (line 8))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting prettytable>=0.7 (from -r /tmp/requirements.txt (line 9))
  Using cached prettytable-3.10.0-py3-none-any.whl.metadata (30 kB)
Collecting python-dateutil (from -r /tmp/requirements.txt (line 10))
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pysyncobj>=0.3.8 (from -r /tmp/requirements.txt (line 11))
  Using cached pysyncobj-0.3.12.tar.gz (41 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/usr/local/lib/python3.12/dist-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/usr/local/lib/python3.12/dist-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/usr/local/lib/python3.12/dist-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by rcknr** [comment]
Could [this](https://pythontest.com/posts/2023/2023-10-02-py312-impimporter/) be helpful?

**Comment by vitabaks** [comment]
Perhaps we will switch from pip to rpm/deb by default for patroni packages.

**Comment by JohnTheNerd** [comment]
I was able to successfully set up the cluster on Ubuntu 24.04 by:

- running `python3 -m pip install --upgrade setuptools --break-system-packages` as root on the nodes
- commenting out the part where dependencies are installed in the Ansible playbook
- installing the following packages via APT:
    - `python3-packaging`
    - `python3-pycparser`
    - `python3-consul`
- installing `patroni[dependencies]` via pip, using the `--break-system-packages` option, which should now succeed
- running the playbook with the parts commented out
- setting the file permissions for `/etc/postgresql/16/main/postgresql.conf` to 644
- rebooting all nodes

not sure how much of this is necessary, but I hope it at least helps!

**Comment by vitabaks** [comment]
> I was able to successfully set up the cluster on Ubuntu 24.04 by

In your case, the key is that you are using consul and you did not need to install the outdated python-etcd package.

**Comment by vitabaks** [comment]
To ensure compatibility with Ubuntu 22.04 (and Python 3.12), the Patroni package will be installed from the deb/rpm package by default.

**Pull request merged**
